[package]
name = "rgis-ui"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2021"
publish = false

[dependencies]
async-channel = "1"
bevy = { version = "0.6", default-features = false, features = [
    # "bevy_dynamic_plugin",
    "bevy_gilrs",
    "bevy_gltf",
    "bevy_winit",
    "render",
] }
bevy_egui = "0.11"
geo-srs = { path = "../geo-srs" }
geo-types = "0.7"
rfd = "0.8"
rgis-layer-id = { path = "../rgis-layer-id" }
rgis-layers = { path = "../rgis-layers" }
rgis-events = { path = "../rgis-events" }
webbrowser = "0.6"
