[package]
name = "rgis-ui"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2021"
publish = false

[dependencies]
bevy = { version = "0.6", default-features = false, features = [
    "bevy_dynamic_plugin",
    "bevy_gilrs",
    "bevy_gltf",
    "bevy_winit",
    "render",
] }
bevy_egui = "0.10"
geo-srs = { path = "../geo-srs" }
geo-types = "0.7"
rgis-layers = { path = "../rgis-layers" }
rgis-renderer = { path = "../rgis-renderer" }
