[workspace]

members = [
    "bevy_prototype_lyon",
    "bevy-earcutr",
    "geo-earcutr",
    "geo-lyon",
    "geo-srs",
    "rgis",
    "rgis-cli",
    "rgis-file-loader",
    "rgis-layers",
]


[profile.release]
debug = true
