[workspace]
members = [
    "geo-bevy",
    "geo-srs",
    "rgis",
    "rgis-camera",
    "rgis-cli",
    "rgis-file-loader",
    "rgis-keyboard",
    "rgis-layers",
    "rgis-mouse",
    "rgis-ui",
    "time-logger",
]
resolver = "2"

[profile.release]
debug = true

[patch.crates-io]
proj = { git = "https://github.com/georust/proj" }
proj-sys = { git = "https://github.com/georust/proj" }
