[workspace]
members = [
    "geo-bevy",
    "rgis-camera",
    "rgis-cli",
    "rgis-events",
    "rgis-file-loader",
    "rgis-keyboard",
    "rgis-layer-id",
    "rgis-layers",
    "rgis-library",
    "rgis-mouse",
    "rgis-settings",
    "rgis-renderer",
    "rgis-ui",
    "rgis",
    "time-logger",
]
resolver = "2"

[profile.release]
debug = true

