[package]
name = "rgis"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]

[dependencies]
geo = "*"
piston = "0.31.4"
piston2d-graphics = "0.21.0"
piston2d-opengl_graphics = "0.42.1"
pistoncore-sdl2_window = "0.40.0"
