[package]
name = "rgis"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "GPL-3.0-only"
edition = "2018"

[dependencies]
colorous = "*"
env_logger = "*"
geo = "0.13"
geojson = { version = "0.18", features = ['geo-types'] }
gl = "0.14"
glutin = "*"
log = "*"
pathfinder_canvas = "*"
pathfinder_color = "*"
pathfinder_content = "*"
pathfinder_geometry = "*"
pathfinder_gl = "*"
pathfinder_renderer = "*"
pathfinder_resources = "*"
rayon = "*"
serde_json = "1.0"

[patch.crates-io]
geo = { git = "https://github.com/georust/geo.git", branch = "master" }
geo-types = { git = "https://github.com/georust/geo.git", branch = "master" }
