[workspace]

members = [
    "geo-bevy",
    "geo-srs",
    "rgis",
    "rgis-camera",
    "rgis-cli",
    "rgis-file-loader",
    "rgis-layers",
    "rgis-ui",
    "time-logger",
]


[profile.release]
debug = true
