[workspace]

members = [
    "geo-bevy",
    "geo-srs",
    "rgis",
    "rgis-camera",
    "rgis-cli",
    "rgis-file-loader",
    "rgis-keyboard",
    "rgis-layers",
    "rgis-mouse",
    "rgis-ui",
    "time-logger",
]

[profile.release]
debug = true

[patch.crates-io]
proj = { path = "../../georust/proj" }
proj-sys = { path = "../../georust/proj/proj-sys" }
