[workspace]
members = [
    "geo-bevy",
    "geo-features",
    "geo-proj-js",
    "rgis-camera",
    "rgis-cli",
    "rgis-events",
    "rgis-file-loader",
    "rgis-keyboard",
    "rgis-layer-id",
    "rgis-layers",
    "rgis-library",
    "rgis-mouse",
    "rgis-network",
    "rgis-renderer",
    "rgis-settings",
    "bevy-jobs",
    "rgis-ui",
    "rgis",
    "time-logger",
]
resolver = "2"

[patch.crates-io]
geo = { git = "https://github.com/georust/geo.git" }

[profile.release]
debug = true
