[workspace]

members = [
    "bevy-earcutr",
    "geo-earcutr",
    "geo-srs",
    "rgis",
    "rgis-cli",
    "rgis-file-loader",
    "rgis-layers",
    "time-logger",
]


[profile.release]
debug = true

[patch.crates-io]
geo-types = { path = '../../georust/geo/geo-types' }
