[workspace]

members = [
    "geo-srs",
    "rgis",
    "rgis-camera",
    "rgis-cli",
    "rgis-file-loader",
    "rgis-layers",
    "time-logger",
]


[profile.release]
debug = true

[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy.git" }
