[package]
name = "rgis"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "GPL-3.0-only"
edition = "2018"

[dependencies]
geo = "0.6"
geojson = "0.9"
gl = "0.14"
glutin = "*"
lazy_static = "1"
pathfinder_canvas = "*"
pathfinder_color = "*"
pathfinder_content = "*"
pathfinder_geometry = "*"
pathfinder_gl = "*"
pathfinder_renderer = "*"
pathfinder_resources = "*"
serde_json = "1.0"
