[package]
name = "rgis"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "GPL-3.0-only"
edition = "2018"

[dependencies]
colorous = "1"
env_logger = "0.7"
geo = "0.14"
geojson = { version = "0.19", features = ['geo-types'] }
gl = "0.14"
glutin = "0.24"
log = "0.4"
rayon = "1"
rgx = "*"
serde_json = "1"
