[package]
name = "rgis"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "GPL-3.0-only"
edition = "2018"

[dependencies]
colorous = "1"
env_logger = "0.7"
geo = { version = "0.14", features = ['use-proj'] }
geojson = { version = "0.19", features = ['geo-types'] }
geo-projected = { path = "./geo-projected" }
gl = "0.14"
glutin = "0.24"
log = "0.4"
pathfinder_canvas = { git = "https://github.com/servo/pathfinder.git" }
pathfinder_color = { git = "https://github.com/servo/pathfinder.git" }
pathfinder_content = { git = "https://github.com/servo/pathfinder.git" }
pathfinder_geometry = { git = "https://github.com/servo/pathfinder.git" }
pathfinder_gl = { git = "https://github.com/servo/pathfinder.git" }
pathfinder_renderer = { git = "https://github.com/servo/pathfinder.git" }
pathfinder_resources = { git = "https://github.com/servo/pathfinder.git" }
rayon = "1"
serde_json = "1"
