[package]
name = "rgis-transform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.7", default-features = false, features = [
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "bevy_ui",
    "wayland",
] }
rgis-events = { path = "../rgis-events" }
rgis-layer-id = { path = "../rgis-layer-id" }
rgis-layers = { path = "../rgis-layers" }
rgis-settings = { path = "../rgis-settings" }
rgis-task = { path = "../rgis-task" }
thiserror = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
geo = { version = "0.21", features = ["use-proj"] }
proj = "0.26"

[target.'cfg(target_arch = "wasm32")'.dependencies]
geo-proj-js = { path = "../geo-proj-js" }
geo = "0.21"
