[package]
name = "rgis-mouse"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.8", default-features = false, features = [
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "bevy_ui",
    "wayland",
] }
bevy_egui = "0.15"
geo = "0.23"
rgis-events = { path = "../rgis-events" }
rgis-settings = { path = "../rgis-settings" }
