[package]
name = "rgis-renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.6", default-features = false, features = [
    "bevy_gilrs",
    "bevy_gltf",
    "bevy_winit",
    "render",
] }
geo-bevy = { path = "../geo-bevy" }
rgis-events = { path = "../rgis-events" }
rgis-layer-id = { path = "../rgis-layer-id" }
rgis-layers = { path = "../rgis-layers" }
time-logger = { path = "../time-logger" }
