[package]
name = "rgis-file-loader"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2021"

[dependencies]
async-channel = "1"
bevy = { version = "0.7", default-features = false, features = [
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "bevy_ui",
    "wayland",
] }
ehttp = "0.2"
geo = "0.21"
geojson = { version = "0.23", features = ["geo-types"] }
rgis-cli = { path = "../rgis-cli" }
rgis-layers = { path = "../rgis-layers" }
rgis-layer-id = { path = "../rgis-layer-id" }
rgis-settings = { path = "../rgis-settings" }
rgis-task = { path = "../rgis-task" }
serde_json = "1"
time-logger = { path = "../time-logger" }
thiserror = "1"
rgis-events = { path = "../rgis-events" }
