[package]
name = "rgis-file-loader"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2021"

[dependencies]
bevy = { version = "0.6", default-features = false, features = [
    # "bevy_dynamic_plugin",
    "bevy_gilrs",
    "bevy_gltf",
    "bevy_winit",
    "render",
] }
futures-lite = "1"
geo-types = "0.7"
geojson = { version = "0.22", features = ["geo-types"] }
rgis-cli = { path = "../rgis-cli" }
rgis-layers = { path = "../rgis-layers" }
serde_json = "1"
time-logger = { path = "../time-logger" }
