[package]
name = "rgis-file-loader"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2021"

[dependencies]
bevy = { version = "0.8", default-features = false, features = [
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "bevy_ui",
    "wayland",
] }
geo = "0.23"
geo-features = { path = "../geo-features" }
geojson = { version = "0.23", features = ["geo-types"] }
geozero = "0.9"
rgis-cli = { path = "../rgis-cli" }
rgis-events = { path = "../rgis-events" }
rgis-network = { path = "../rgis-network" }
bevy_jobs = { git = "https://github.com/frewsxcv/bevy_jobs" }
serde_json = "1"
time-logger = { path = "../time-logger" }
thiserror = "1"
