[package]
name = "rgis-file-loader"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2018"

[dependencies]
bevy = "0.4"
geo-types = "0.6"
geojson = "0.20"
rgis-cli = { path = "../rgis-cli" }
rgis-layers = { path = "../rgis-layers" }
serde_json = "1"
time-logger = { path = "../time-logger" }
