[package]
name = "rgis"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy = { version = "0.8", default-features = false, features = [
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "bevy_ui",
    "wayland",
] }
geo = "0.22"
geo-bevy = { path = "../geo-bevy" }
rgis-camera = { path = "../rgis-camera" }
rgis-cli = { path = "../rgis-cli" }
rgis-file-loader = { path = "../rgis-file-loader" }
rgis-keyboard = { path = "../rgis-keyboard" }
rgis-layers = { path = "../rgis-layers" }
rgis-mouse = { path = "../rgis-mouse" }
rgis-network = { path = "../rgis-network" }
rgis-renderer = { path = "../rgis-renderer" }
rgis-settings = { path = "../rgis-settings" }
bevy-jobs = { path = "../bevy-jobs" }
rgis-transform = { path = "../rgis-transform" }
rgis-ui = { path = "../rgis-ui" }
time-logger = { path = "../time-logger" }
rgis-events = { path = "../rgis-events" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
bevy-web-resizer = "3.0"
wasm-bindgen = "0.2"

# wasm-opt results in a segfault on Linux in CI
[package.metadata.wasm-pack.profile.release]
wasm-opt = false
