[package]
name = "rgis"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2018"

[dependencies]
bevy = "0.3"
bevy_prototype_lyon = "0.1"
env_logger = "0.8"
geo = { version = "0.15" }
geojson = { version = "0.20", features = ['geo-types'] }
geo-lyon = { path = "../geo-lyon" }
geo-srs = { path = "../geo-srs" }
log = "0.4"
rgis-cli = { path = "../rgis-cli" }
rgis-file-loader = { path = "../rgis-file-loader" }
rgis-layers = { path = "../rgis-layers" }
