[package]
name = "rgis"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2018"

[dependencies]
bevy = { version = "0.4", default-features = false, features = [
    "bevy_dynamic_plugin",
    "bevy_gilrs",
    "bevy_gltf",
    "bevy_wgpu",
    "bevy_winit",
    "render",
] }
# bevy = { version = "0.4", features = ['trace' , 'trace_chrome'] }
geo = { version = "0.17" }
geojson = { version = "0.20", features = ['geo-types'] }
geo-bevy = { path = "../geo-bevy" }
geo-srs = { path = "../geo-srs" }
rgis-camera = { path = "../rgis-camera" }
rgis-cli = { path = "../rgis-cli" }
rgis-file-loader = { path = "../rgis-file-loader" }
rgis-keyboard = { path = "../rgis-keyboard" }
rgis-layers = { path = "../rgis-layers" }
rgis-mouse = { path = "../rgis-mouse" }
rgis-ui = { path = "../rgis-ui" }
time-logger = { path = "../time-logger" }
