[package]
name = "rgis"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy = { version = "0.6", default-features = false, features = [
    # "bevy_dynamic_plugin",
    "bevy_gilrs",
    "bevy_gltf",
    "bevy_winit",
    "render",
] }
# bevy = { version = "0.6", features = ['trace' , 'trace_chrome'] }
geo = { version = "0.19" }
geojson = { version = "0.20", features = ['geo-types'] }
geo-bevy = { path = "../geo-bevy" }
geo-srs = { path = "../geo-srs" }
rgis-camera = { path = "../rgis-camera" }
rgis-cli = { path = "../rgis-cli" }
rgis-file-loader = { path = "../rgis-file-loader" }
rgis-keyboard = { path = "../rgis-keyboard" }
rgis-layers = { path = "../rgis-layers" }
rgis-mouse = { path = "../rgis-mouse" }
rgis-renderer = { path = "../rgis-renderer" }
rgis-ui = { path = "../rgis-ui" }
time-logger = { path = "../time-logger" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
bevy-web-resizer = "0.1"
wasm-bindgen = "0.2"

# wasm-opt results in a segfault on Linux in CI
[package.metadata.wasm-pack.profile.release]
wasm-opt = false
