[package]
name = "geo-file-loader"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
time-logger = { path = "../time-logger" }
geo = "0.23"
geo-features = { path = "../geo-features" }
geojson = { version = "0.23", features = ["geo-types"] }
geozero = "0.9"
serde_json = "1"
thiserror = "1"
