[package]
name = "geo-file-loader"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bytes = "1"
time-logger = { path = "../time-logger" }
geo = "0.27"
geo-features = { path = "../geo-features" }
geozero = { version = "0.11", features = ["with-wkt"] }
geozero-shp = { git = "https://github.com/georust/geozero.git" }
thiserror = "1"
