[package]
name = "geo-bevy"
version = "0.0.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2018"
publish = false

[dependencies]
bevy_log = "0.5"
bevy_render = "0.5"
bevy-earcutr = "0.2"
geo = "0.17"
