[package]
name = "geo-bevy"
version = "0.0.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2021"
publish = false

[dependencies]
bevy_log = "0.7"
bevy_render = "0.7"
bevy-earcutr = "0.5"
geo = "0.20"
