[package]
name = "geo-bevy"
version = "0.0.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2021"
publish = false

[dependencies]
bevy_log = "0.6"
bevy_render = "0.6"
bevy-earcutr = "0.4"
geo = "0.19"
