[package]
name = "geo-bevy"
version = "0.0.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2021"
publish = false

[dependencies]
bad = "0.1"
bevy_log = "0.8"
bevy_render = "0.8"
bevy-earcutr = "0.6"
geo = "0.22"
