[package]
name = "transform"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
geodesy = { version = "0.12", default-features = false }
crs-definitions = "0.3"
geo = "0.27"
thiserror = "1"
