[package]
name = "bevy-web-resizing"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_arch = "wasm32")'.dependencies]
crossbeam-channel = "*"
bevy = "0.6"
winit = "*"
wasm-bindgen = "*"
web-sys = "*"
