[package]
name = "geo-srs"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2018"

[dependencies]
geo = { version = "0.17" }
proj = { version = "*", features = ['bundled_proj'] }
