[package]
name = "rgis-layers"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2018"
publish = false

[dependencies]
bevy = { version = "0.4", default-features = false, features = [
    "bevy_dynamic_plugin",
    "bevy_gilrs",
    "bevy_gltf",
    "bevy_wgpu",
    "bevy_winit",
    "render",
] }
colorous = "1"
geo = "0.15"
geo-srs = { path = "../geo-srs" }
time-logger = { path = "../time-logger" }
serde_json = "1"
