[package]
name = "rgis-layers"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2021"
publish = false

[dependencies]
bevy = { version = "0.6", default-features = false, features = [
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "bevy_ui",
] }
colorous = "1"
rgis-events = { path = "../rgis-events" }
rgis-layer-id = { path = "../rgis-layer-id" }
time-logger = { path = "../time-logger" }
serde_json = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
geo = { version = "0.19", features = ["use-proj"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
geo-proj-js = { path = "../geo-proj-js" }
geo = { version = "0.19" }
