[package]
name = "geo-proj-js"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = { version = "0.3", default-features = false }
web-sys = { version = "0.3", default-features = false, features = ['Window'] }
wasm-bindgen = "0.2"
geo = { version = "0.19" }
